apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      name: airflow
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-container
          image: ds4ouj/custom-airflow
          imagePullPolicy: Always
      restartPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-temp
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
