apiVersion: v1
kind: Service
metadata:
  name: airflow
spec:
  type: NodePort
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  externalIPs:
    - 192.168.0.13
