apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-service-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: "demo-service.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 8080